apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: dvwa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: dvwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: local-path-pvc
      containers:
      - image: mariadb:10
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: dvwa123456
        - name: MARIADB_USER
          value: dvwa
        - name: MARIADB_PASSWORD
          value: dvwa
        - name: MARIADB_DATABASE
          value: dvwa
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: dvwa
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
  clusterIP: None
